# Set the default terminal type for proper key handling
set -g default-terminal "tmux-256color"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Fix shift-enter
bind-key -T root S-Enter send-keys Escape "[13;2u"

set -g mouse on

